version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prefect
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - orderline-dw-network

  prefectserver:
    build:
      context: .
      dockerfile: docker/prefectserver/Dockerfile
    depends_on:
      - postgresdb
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
      # PREFECT_SERVER_API_PORT: 4444
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://postgres:postgres@postgresdb:5432/prefect"
    ports:
      - "4200:4200"
    networks:
      - orderline-dw-network


  prefectflows:
    build:
      context: .
      dockerfile: docker/flows/Dockerfile
    depends_on:
      - prefectserver
    environment:
      # OLTP database
      OLTP_DB_SERVER: mischa-orderline-oltp-test.database.windows.net
      OLTP_DB_NAME: orderline-oltp-test
      OLTP_USERNAME: $OLTP_USERNAME
      OLTP_PASSWORD: $OLTP_PASSWORD
      # Data warehouse
      DW_DB_SERVER: mischa-orderline-dw-run2.database.windows.net
      DW_DB_NAME: orderline-dw
      DW_USERNAME: $DW_USERNAME
      DW_PASSWORD: $DW_PASSWORD
      # Prefect
      PREFECT_LOGGING_EXTRA_LOGGERS: orderline_dw
      PREFECT_API_URL: http://prefectserver:4200/api
    networks:
      - orderline-dw-network

networks:
  orderline-dw-network:

volumes:
  postgres-data:
